Includes Redis-Replay Adapter Logic
triggermesh/brokers pull request #126
Opened 2023-03-06 16:54 UTC by JeffNeff

This PR adds the Redis-Replay adapter logic alongside our broker implementations.

2023-03-08 18:54 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +		// case "extension":
I have not figured out how to handle the extensions yet.. possibly someone has a suggestion for this part?

2023-03-08 18:55 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +		case "schemaurl":
I left this in here to get us thinking about the concept of taking a URL that points to a schema and then performing validation against said schema before passing along the replay events.

2023-03-08 18:55 UTC, JeffNeff commented on pkg/replay/redis/types.go
> +// Copyright 2022 TriggerMesh Inc.
wrong date
```suggestion
// Copyright 2023 TriggerMesh Inc.
```

2023-03-08 18:55 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +// Copyright 2022 TriggerMesh Inc.
wrong date
```suggestion
// Copyright 2023 TriggerMesh Inc.
```

2023-03-08 18:56 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +// Copyright 2022 TriggerMesh Inc.
wrong date
```suggestion
// Copyright 2023 TriggerMesh Inc.
```

2023-03-08 18:56 UTC, JeffNeff commented on cmd/replay/redis/Dockerfile
> +# Copyright 2022 TriggerMesh Inc.
wrong date
```suggestion
# Copyright 2023 TriggerMesh Inc.
```

2023-03-08 19:06 UTC, odacremolbap requested changes

2023-03-08 19:06 UTC, odacremolbap commented on docker-compose.yaml
> +services:
I don't see this here.
I know it helps you, but we have the `.local` folder where we can keep the "opinionated" files like this.

It could also fit, in `docs` if you want to write a guide on `testing with docker compose`. If you want you can create a PR on that and add an MD and this file in it.

2023-03-09 15:45 UTC, JeffNeff commented on go.mod
> +	github.com/triggermesh/triggermesh v1.24.0
No! we do not need this! I will update.

2023-03-09 17:02 UTC, FranBarrera requested changes

2023-03-09 17:02 UTC, FranBarrera commented on pkg/replay/redis/adapter.go
> +			a.Logger.Errorf("Error parsing event timestamp: %v", err)
I think this should have a different error message, it's duplicated

2023-03-09 18:57 UTC, odacremolbap commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
There is another entry like this in this file pointing to v9.0.2-rc2

Can we use this updated version on remove the other entry.

2023-03-09 19:27 UTC, JeffNeff commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
sorry.. i thought I adjusted that.. I dont know how he got back in there.

2023-03-13 18:14 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +			a.Logger.Errorf("Error parsing event timestamp: %v", err)
mhm.. im not positive what you are asking. there are two similar errors here because we are parsing two timestamps. but i think we need both.

2023-03-13 18:33 UTC, JeffNeff commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
mhm.. When i remove one it breaks the other.

2023-03-14 12:01 UTC, odacremolbap commented on pkg/replay/redis/adapter.go
> +				return result
If there is an error, stopping the processing is an option although I rather continue processing.

The error could be better informed, including the event ID.
Most probably we will be getting duplicate log entries for errors, one written here, and the error being also written by the caller.

2023-03-14 12:03 UTC, odacremolbap commented on pkg/replay/redis/adapter.go
> +	}
I think Redis might have something less opinionated that means "since the beginning"

2023-03-14 13:52 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +			ctx := cloudevents.ContextWithTarget(context.Background(), a.Sink)
you are right. this does not make much since

2023-03-14 13:52 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +	val, err := a.Client.XRange(context.Background(), "triggermesh", "-", "+").Result()
I suppose.. maybe.. ill have to play with that.

2023-03-15 15:41 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +	val, err := a.Client.XRange(context.Background(), "triggermesh", "-", "+").Result()
.. i think I prefer it this way. I will change it to that if you want it that way tho.

2023-03-16 19:19 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +	// create a new zap logger
```suggestion
```

2023-03-16 19:21 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +		return
```suggestion
```

2023-03-16 19:24 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +	// create a new cloudevent client
create the context with target here.

2023-03-16 19:26 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +func (a *ReplayAdapter) ReplayEvents() error {
```suggestion
func (a *ReplayAdapter) ReplayEvents(ctx context.Context) error {
```

2023-03-16 19:27 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +	// create a new cloudevent client
```suggestion
	ctx := cloudevents.ContextWithTarget(context.Background(), a.Sink)
```

2023-03-16 19:27 UTC, JeffNeff commented on cmd/replay/redis/main.go
> +	if err := replayAdapter.ReplayEvents(); err != nil {
```suggestion
	if err := replayAdapter.ReplayEvents(ctx); err != nil {
```

2023-03-16 19:36 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +	if len(events) != 0 && a.Sink != "" {
```suggestion
	if len(events) != 0 {
```

2023-03-16 19:37 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +			eventCounter++
move till after it is sent successfully

2023-03-16 19:41 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +		case "schemaurl":
remove this

2023-03-16 19:41 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +		start = "2020-02-13T16:01:12Z"
```suggestion
		start = "-"
```

2023-03-16 19:43 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +	// if the end timestamp is empty or 0, set it to the current time
move all time parsing logic to cmd

2023-03-16 19:43 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +		// extract the '-0' from the event timestamp
it should remove all after `-` not just 0

2023-03-17 00:45 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +			eventCounter++
```suggestion
```

2023-03-17 00:46 UTC, JeffNeff commented on pkg/replay/redis/adapter.go
> +			}
```suggestion
			}
			eventCounter++
```

2023-06-22 06:31 UTC, odacremolbap commented
has been added at https://github.com/triggermesh/brokers/pull/160
closing this one.

thanks  @JeffNeff

2023-06-22 06:31 UTC, closed without merging