Adding CA Certificate for RedisBroker
triggermesh/brokers pull request #130
Opened 2023-03-23 20:54 UTC by coding-trees

2nd part to adding CA certificate support for RedisBroker as described in this issue https://github.com/triggermesh/brokers/issues/129

2023-03-23 20:56 UTC, coding-trees commented
Hi @odacremolbap  - let me know if there are any other docs or repos that will need to be updated with information re: CA Certificates. Thanks

2023-03-24 09:13 UTC, odacremolbap requested changes
Thanks a lot for your PRs @coding-trees 
This is looking good.

I asked for a couple of nits.

At one of them I am suggesting to validate that CA Certificate is not informed alongside Skip Verify. That would be done [here](https://github.com/triggermesh/brokers/blob/d92049ac4e117df86343b175867e4b7114312c15/pkg/backend/impl/redis/cmd.go#L29-L44) and would probably look like this:

```go
	if ra.TLSCACertificate != "" && ra.TLSSkipVerify {
		msg = append(msg, "only one of skip verify or CA certificate can be informed")
	}

```

2023-03-24 09:13 UTC, odacremolbap commented on pkg/backend/impl/redis/redis.go
> +			}
InsecureSkipVerify should be false when the CA is informed. If a user specifies incompatible parameters we should validate and throw an error (I'll add a comment on this), so that first line can be removed.

There is a slightly more idiomatic way of doing those [conditionals in go using a local variable to the if block](https://go.dev/doc/effective_go#if).

```go
if ok := ... ; !ok {
  ...
}
```

The returned error already contains the stacktrace, there is no need to wrap an error inside of another here. I left the internal one that you already created ([non capitalised](https://github.com/golang/go/wiki/CodeReviewComments#error-strings))

```suggestion
			roots := x509.NewCertPool()
			if ok := roots.AppendCertsFromPEM([]byte(s.args.TLSCACertificate)); !ok {
				return errors.New("not valid CA Cert format")
			}
```

2023-03-24 09:13 UTC, odacremolbap commented on README.md
> +REDIS_CA_CERTIFICATE="-----BEGIN CERTIFICATE-----abc123-----END CERTIFICATE-----"
This is a simple example of using environment variables, and skip verify is already informed. I would move this entry from here, to https://github.com/triggermesh/brokers#tls-enabled-redis , and would use your new parameter instead of the skip verify.

2023-03-24 09:13 UTC, odacremolbap commented on README.md
> +
We have the full list of parameters [here](https://github.com/triggermesh/brokers#broker-parameters).
Maybe we can remove this entry and add a line next to the already existing `redis.tls-enabled` and `redis.tls-skip-verify`.

2023-03-24 17:44 UTC, coding-trees commented on pkg/backend/impl/redis/cmd.go
> +	CACertificate string `help:"CA Certificate to connect to Redis." env:"CA_CERTIFICATE"`
Sounds good, I updated the naming

2023-03-24 17:45 UTC, coding-trees commented on pkg/backend/impl/redis/redis.go
> +			}
Thanks, looks much cleaner this way.

2023-03-24 17:45 UTC, coding-trees commented on README.md
> +
Removed and updated the parameters

2023-03-24 17:50 UTC, coding-trees commented
Hi @odacremolbap  - Thank you for the review and feedback, I believe I have applied all of the changes you have suggested - if there is anything missing or anything is still kind of "off" please let me know. I don't mind any and all suggestions, feel free to nit pick; just want to make sure the changes are up to snuff.

2023-03-25 10:04 UTC, odacremolbap approved these changes

2023-03-25 11:39 UTC, merged